# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [108]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [109]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [142]:
A.size

6

In [143]:
A.shape

(2, 3)

In [144]:
A.ndim

2

In [145]:
A.dtype

dtype('int32')

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [146]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [147]:
B-C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [148]:
B*C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [149]:
B@C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [150]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [151]:
"""e^(each element elementwise)"""
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [152]:
"""calculates minimum in the matrix"""
np.min(B)

1

In [153]:
"""calculates minimum in last row"""
np.min(B[2,0:])

7

In [154]:
"""calculates minimum in last column"""
np.min(B[0:,2])

3

In [155]:
"""calculates index value at the minimum"""
np.argmin(B)

0

In [156]:
np.argmin(B, axis=0)

array([0, 0, 0], dtype=int64)

In [157]:
np.sum(B)

45

In [158]:
np.mean(B, axis=1)

array([2., 5., 8.])

In [159]:
np.median(B, axis=1)

array([2., 5., 8.])

In [160]:
e=B[:].min()

In [161]:
D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(D[0, 0:2])

[1 2]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [162]:
print(A)

[[ 2  1 -1]
 [ 1 -1  1]]


In [163]:
A[1]

array([ 1, -1,  1])

**Answer:you print the whole matrix/row. There will be complete slices in the other dimensions**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [164]:
A

array([[ 2,  1, -1],
       [ 1, -1,  1]])

In [165]:
for i in A:
    print(i)

[ 2  1 -1]
[ 1 -1  1]


In [134]:
for i in A.ravel():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [166]:
"""three axes means three dimensions size is product of shape(like "cube"). The array has index tuples in three directions.
for b it means that it is two matrices with three rows and then the number of columns that becomes product 30 in this case
5 columns"""
a = np.arange(30)
b = a.reshape(2,3,-1)
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [167]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])



print(m1+ m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [168]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [138]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print(A+b)

[[1 2]
 [3 4]]
[2 2]
[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [169]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [170]:
def add_mult_matrices(matrix1,matrix2,a_m):
    if not isinstance(matrix1,np.ndarray) or not isinstance(matrix2,np.ndarray):
        raise Exception("input not array") 
    if a_m == "add":
        if not matrix1.shape == matrix2.shape:
            print("can only add matrices if same shape")
        else:
            return matrix1 + matrix2
    elif a_m == "multiply":
        if not matrix1.shape[1] == matrix2.shape[0]:
            print("matrices must be multipliable")
        else:
            return matrix1 @ matrix2
            
  
            
    

In [171]:
O=np.arange(9).reshape(3,3)
P=np.arange(9).reshape(3,3)

In [172]:
print(O)
print(P)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Chap2. Question 2**

In [174]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [175]:
AB=add_mult_matrices(A,B,"multiply")
AC=add_mult_matrices(A,C,"multiply")
print(AB)
print(AC)
print(AB==AC)
print(B==C)

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


**Chap2. Question 3**

In [176]:
A=np.array([[1,1,1],[1,2,3],[1,3,4]])
D=np.array([[2,0,0],[0,3,0],[0,0,4]])
AD=add_mult_matrices(A,D,"multiply")
DA=add_mult_matrices(D,A,"multiply")
print("AD:",AD)
print("DA:",DA)

AD: [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA: [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [177]:
M1=np.array([[1,-1],[-1,1]])
M2=np.array([[-1,1],[1,-1]])
M1M2=add_mult_matrices(M1,M2,"multiply")
print("M1M2", M1M2)

M1M2 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [178]:
M1=np.array([[5,6],[4,5]])
M2=np.array([[6,4],[3,3]])

In [179]:
invM1=np.linalg.inv(M1)
print(invM1)
print(M1 @ invM1)
print(np.allclose(M1 @ invM1,np.eye(2)))

[[ 5. -6.]
 [-4.  5.]]
[[ 1.00000000e+00  0.00000000e+00]
 [-3.55271368e-15  1.00000000e+00]]
True


In [180]:
invM2=np.linalg.inv(M2)
print(invM2)
print(M2 @ invM2)
print(np.allclose(M2 @ invM2,np.eye(2)))

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]
[[1. 0.]
 [0. 1.]]
True


**Quiz p.19, Question 3**

In [181]:
M=np.array([[2,2],[1,2]])
inv_M=np.linalg.inv(M)
print(inv_M)
print(M @ inv_M)
print(np.allclose(M @ inv_M,np.eye(2)))

[[ 1.  -1. ]
 [-0.5  1. ]]
[[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [182]:
A=np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
a=np.array([-7,5,2])
print(A)
print(a)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]
[-7  5  2]


In [183]:
solution=np.linalg.solve(A,a)
print(solution)

[ 3.  4. -6.]


In [184]:
"""verification av rätt svar"""
A @ solution

array([-7.,  5.,  2.])

**Chap10. Question 1 b)**

In [185]:
A=np.array([[1,-2,3],[-1,3,-1],[2,-5,5]])
a=np.array([1,-1,1])
print(A)
print(a)

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]
[ 1 -1  1]


In [186]:
solution=np.linalg.solve(A,a)
print(solution)

[ 8.  2. -1.]


In [187]:
"""verification av rätt svar"""
A @ solution

array([ 1., -1.,  1.])

**Chap 12. Question 1**

In [188]:
M=np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
print(M)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]


In [189]:
invM=np.linalg.inv(M)
print(invM)

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?** 

"""If the base attribute returns "None" it is a copy. V1 will be changed when we change last element to 123 because it is a copy"""  

In [190]:
v1 = np.arange(4)
v2 = v1[-3:]
print(v1)
print(v2)

[0 1 2 3]
[1 2 3]


In [191]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [192]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  1   2 123]
